"""empty message

Revision ID: 7bffc6369481
Revises: e7b7d1f65494
Create Date: 2016-11-12 22:44:26.694390

"""

# revision identifiers, used by Alembic.
revision = '7bffc6369481'
down_revision = 'e7b7d1f65494'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    ### end Alembic commands ###
