"""empty message

Revision ID: 7ebed9030365
Revises: c870f3cc156d
Create Date: 2016-11-12 18:47:24.629126

"""

# revision identifiers, used by Alembic.
revision = '7ebed9030365'
down_revision = 'c870f3cc156d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content2', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('content2')

    ### end Alembic commands ###
