"""empty message

Revision ID: 8cc73aef6d6b
Revises: 9bd7b6743a19
Create Date: 2016-11-12 21:31:45.176706

"""

# revision identifiers, used by Alembic.
revision = '8cc73aef6d6b'
down_revision = '9bd7b6743a19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_url', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pic_url')
        batch_op.drop_column('name')

    ### end Alembic commands ###
