"""empty message

Revision ID: c61096e5e8da
Revises: 7ebed9030365
Create Date: 2016-11-12 18:48:08.501971

"""

# revision identifiers, used by Alembic.
revision = 'c61096e5e8da'
down_revision = '7ebed9030365'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('content2')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content2', sa.TEXT(), nullable=True))

    ### end Alembic commands ###
