"""empty message

Revision ID: c870f3cc156d
Revises: a90589c0f4a3
Create Date: 2016-11-12 18:34:40.820556

"""

# revision identifiers, used by Alembic.
revision = 'c870f3cc156d'
down_revision = 'a90589c0f4a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments') as batch_op:
        batch_op.drop_column('title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.VARCHAR(length=255), nullable=True))
    ### end Alembic commands ###
