"""empty message

Revision ID: e7b7d1f65494
Revises: 8cc73aef6d6b
Create Date: 2016-11-12 21:39:04.489403

"""

# revision identifiers, used by Alembic.
revision = 'e7b7d1f65494'
down_revision = '8cc73aef6d6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_id', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('facebook_id')

    ### end Alembic commands ###
